### ISSUE TITLE
W540 и Coreboot

### ISSUE THREAD

**Issue by lemenkov** [ThinkPadThink/Thinkpadthinkpad#12]
Народ, а откуда инфа, что W540 поддерживает Coreboot? Он насколько идентичен с W541?

**Comment by ThinkPadThink** [comment]
Вероятно, я ошибся. W541 есть в доках. А 540 нет. Скорее всего не заработает.
Я видел только T440p и W541. Остальные только предполагал на самом деле. Железо - то похожее у них. Но видимо нет.
